config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      confirmations: 'users/confirmations'
    }
    
  root to:'gym_apps#index'
  resources :gym_apps
  get "/lessons",to:"lessons#index"
  get "/lessons/:id",to:"lessons#show",as:"lesson"
  get "/items",to:"items#index"
  get "/items/:id",to:"items#show",as:"item"
  get "/points",to:"points#index"
  resources :reservations, only: [:index,:show, :create, :destroy]
    namespace :management do
        resources :lessons
        resources :items
        get "/authenticate",to:"session#new"
        post "/authenticate",to:"session#create"
        resources :users do
          member do
            post "points",to:"users#point"
          end
        end

        get "/logout",to:"session#destroy"
        
    end
    get "/login",to:"session#new"
end

app/models/item.rb
class Item < ApplicationRecord
    has_one_attached :image
    
    validates :name,presence: true
    validates :price,presence: true
    validates :stock,presence: true
    validates :description,presence: true
end

app/controllers/gym_apps/items_controller.rb
class ItemsController < ApplicationController
  # before_action :set_item, only: [:show,:edit,:update,:destroy ]


  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update

  end

  # DELETE /items/1 or /items/1.json
  def destroy

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    # def item_params
    #   params.require(:item).permit(:name, :price, :stock, :description, :image)
    # end
end

app/controllers/items_controller.rb
class ItemsController < UserController
  before_action :set_item, only: [:show]


  # GET /items or /items.json
  def index
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true).page(params[:page]).per(5)
  end

  # GET /items/1 or /items/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    # def item_params
    #   params.require(:item).permit(:name, :price, :stock, :description, :image)
    # end
end

app/controllers/management/items_controller.rb
class Management::ItemsController < ManagementController
  before_action :set_item, only: [:show,:edit,:update,:destroy ]
  # GET /items or /items.json
  def index
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true).page(params[:page]).per(5)
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to [:management,@item], notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
      if @item.update(item_params)
        redirect_to [:management,@item], notice: "Item was successfully updated."
      else
         render :edit
      end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to management_items_path, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :price, :stock, :description, :image)
    end

end

app/controllers/management/lessons_controller.rb
class Management::LessonsController < ManagementController
    before_action :set_lesson,only:[:edit,:update,:destroy]

    def index
        @q = Lesson.ransack(params[:q])
        @lessons = @q.result(distinct: true).page(params[:page]).per(5)
    end
    
    def show
        @lesson = Lesson.includes([:users]).find(params[:id])
    end
    
    def new
        @lesson = Lesson.new
    end
    
    def create
        lesson_params = set_params
        @lesson = Lesson.new(lesson_params)
        
        if @lesson.save
            flash[:notice] = "succeed"
            redirect_to management_lessons_path
        else
            flash.now[:alert] = "failed"
            render :new
        end
    end
    
    def update
        # @lesson = Lesson.find(params[:id])      
        lesson_params = set_params
        if @lesson.update(lesson_params)
            flash[:notice] = "Item was successfully updated."
            redirect_to management_lesson_path(@lesson)
        else
            flash.now[:alert] = "Item was unsuccessfully updated."
            render :edit
        end
    end
    
    def edit

    end
    
    def destroy
        @lesson.discard
        flash[:notice] = "Item was successfully destroyed."
        redirect_to management_lessons_path
    end

    
    private
    
    def set_lesson
        @lesson = Lesson.find(params[:id])
    end
    
    def set_params
        params.require(:lesson).permit(:title,:level,:category,:started_at,:description,:price,:instructor,:limits,:image)
    end

end

app/controllers/management/session_controller.rb
class Management::SessionController < ManagementController
    before_action :login,except: [:new,:create]
    
    def new
    end
    
    def create
        if params[:code] == Rails.application.credentials.code
            session[:auth] = true
            redirect_to management_lessons_path
        else
            session[:auth] = false
            flash.now[:alert] = "The authorization code is different."
            render :new
        end
    end
    
    def destroy
        session[:auth] = false
        redirect_to management_authenticate_path
    end
end

app/controllers/management/users_controller.rb
class Management::UsersController < ManagementController
    before_action :set_user,only:[:show,:edit,:point,:update,:destroy]
    # before_action :set_q,only: [ :index,:search]
    
    def index
        @q = User.ransack(params[:q])
        @users = @q.result(distinct: true).page(params[:page]).per(5)
    end
    
    def point
        @user.point += params[:point].to_i
        @user.save
        redirect_to management_user_path(params[:id])
    end

    def show
        @user = User.includes([:lessons]).find(params[:id])
    end
    
    def edit
    end
    
    def update
        user_params = set_params
        if @user.update(user_params)
            flash[:notice] = "Item was successfully updated."
            redirect_to management_user_path(@user)
        else
            flash[:alert] = "Item was unsuccessfully updated."
            render :edit
        end
    end

    def destroy
        @user.destroy
        flash[:notice] = "Item was successfully destroyed."
        redirect_to management_users_path
    end
    
    private

    def set_user
        @user = User.find(params[:id])
    end

    def set_params
        params.require(:user).permit(:email,:name,:point,:birthday,:address,:sex)
    end
end

app/controllers/management_controller.rb
class ManagementController < ApplicationController
    layout 'management'
    before_action :login

    def login
      unless session[:auth]
        redirect_to management_authenticate_path
      end
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/management/items/_form.html.erb
  <%= form_with(model:[:management,item], local: true) do |form| %>
    <% if item.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>
        <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <table class="table-striped">
    <thead>
      <tr>
        <th>入力項目</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>商品名</td>
        <td><%= form.text_field :name,class:"form-control input-form" %></td>
      </tr>
      <tr>
        <td>値段（税抜）</td>
        <td><%= form.number_field :price,class:"form-control input-form" %></td>
      </tr>
      <tr>
        <td>在庫</td>
        <td><%= form.number_field :stock,class:"form-control input-form" %></td>
      </tr>
      <tr>
        <td>概要</td>
        <td><%= form.text_area :description,class:"form-control memo input-form" %></td>
      </tr>      
    </tbody>
  </table>
    
    <%= form.file_field :image,class:"management-image" %><br> 
    <div class="actions page-top">
      <%= form.submit "登録",class:"btn btn-success"%>
    </div>
  <% end %>

app/views/management/items/edit.html.erb
<div class="container">
    <div class="page-top mb-5">
        <h1>商品情報編集  <%= link_to '【詳細】', [:management,@item],class:"link-info" %></h1>        
        <%= link_to '一覧', management_items_path,class:"btn btn-secondary" %>        
    </div>
    <%= render 'form', item: @item %>
</div>

app/views/management/items/index.html.erb
<div class="container">
  <!--<p id="notice"><%= notice %></p>-->
  <div class="page-top mb-4">
    <h1 class="page-title">商品一覧</h1>
    <%= link_to '新規商品登録', new_management_item_path,class:"btn btn-success" %>
  </div>
  <h2>【検索条件入力欄】</h2>
  <div class="card-body">
      <%= search_form_for @q,url: management_items_path do |f| %>
            <p>商品名：<%= f.search_field :name_cont,placeholder: "name", class:"card-input" %></p>
            <p>値段：<%= f.search_field :price_lt,placeholder: "maximum amount", class:"card-input" %></p>
            <div class="page-top">
                <%= button_tag sanitize('<i class="fas fa-search"></i>検索'),:type => "submit",:class => "btn btn-primary"%>
            </div>
      <% end %>
  </div>
  <table class="table-striped">
    <thead>
      <tr>
        <th>商品名</th>
        <th>値段(税抜)</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.name %></td>
          <td>￥<%= item.price.to_s(:delimited,delimiter:',') %>円</td>
          <td><%= link_to '【詳細】', management_item_path(item),class:"link-info"%>
              <%= link_to '【編集】', edit_management_item_path(item),class:"link-edit" %>
              <%= link_to '【削除】', management_item_path(item), method: :delete, data: { confirm: 'Are you sure?'},class:"link-delete" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @items %>
</div>

app/views/management/items/new.html.erb
<div class="container">
    <div class="page-top mb-5">
        <h1>新規商品登録</h1>        
        <%= link_to '一覧', management_items_path,class:"btn btn-secondary" %>        
    </div>
    <%= render 'form', item: @item %>
</div>    
    

app/views/management/items/show.html.erb
<!--運営側商品詳細-->
<div class="container">
    <div class="btn-margin">

    <div class="page-top">
      <%= link_to '一覧', management_items_path,class:"btn btn-secondary" %>      
    </div>

  </div>
  <div class="content mb-5">
    <div class="show-image">
      <%= image_tag @item.image if @item.image.attached? %><br>    
    </div>
    <div class="description">
      <h1><%= @item.name%><%= link_to '【編集】', edit_management_item_path(@item),class:"link-edit"%></h1>
      <p>値段:<span class="item-price">￥<%= @item.price.to_s(:delimited,delimiter:',') %></span>円</p>
      <p>在庫:<span class="item-stock"><%= @item.stock %></span></p>
      <p>概要:<span class="item-description"><%= @item.description %></span></p>
    </div>  
  </div>
</div>