config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      confirmations: 'users/confirmations'
    }
    
  root to:'gym_apps#index'
  resources :gym_apps
  get "/lessons",to:"lessons#index"
  get "/lessons/:id",to:"lessons#show",as:"lesson"
  get "/items",to:"items#index"
  get "/items/:id",to:"items#show",as:"item"
  get "/points",to:"points#index"
  resources :reservations, only: [:index,:show, :create, :destroy]
    namespace :management do
        resources :lessons
        resources :items
        get "/authenticate",to:"session#new"
        post "/authenticate",to:"session#create"
        resources :users do
          member do
            post "points",to:"users#point"
          end
        end

        get "/logout",to:"session#destroy"
        
    end
    get "/login",to:"session#new"
end

app/controllers/gym_apps/items_controller.rb
class ItemsController < ApplicationController
  # before_action :set_item, only: [:show,:edit,:update,:destroy ]


  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update

  end

  # DELETE /items/1 or /items/1.json
  def destroy

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    # def item_params
    #   params.require(:item).permit(:name, :price, :stock, :description, :image)
    # end
end

app/controllers/gym_apps/lessons_controller.rb
class Management::LessonsController < ManagementController
    # before_action :set_lesson,only:[:show,:edit,:update]

    def index
        @lessons = Lesson.all
        # @lessons = @lessons.where(title: params[:title]) if params[:title].present?
        # @lessons = @lessons.where(started_at: params[:started_at]) if params[:started_at].present?
        # @lessons = @lessons.where(category: params[:category]) if params[:category].present?
    end
    
    def show
        # @lesson = Lesson.find(params[:id])
    end
    
    def new
        @lesson = Lesson.new
    end
    
    def create
        # lesson_params = set_params
        # @lesson = Lesson.new(lesson_params)
        
        # if @lesson.save
        #     flash[:notice] = "登録完了"
        #     redirect_to management_lessons_path
        # else
        #     flash.now[:alert] = "登録失敗"
        #     render :new
        # end
    end
    
    def update
        # @lesson = Lesson.find(params[:id])      
        # lesson_params = set_params
        # if @lesson.update(lesson_params)
        #     flash[:notice] = "レッスン内容を更新しました。"
        #     redirect_to management_lesson_path(@lesson)
        # else
        #     flash.now[:alert] = "更新に失敗しました。"
        #     render :edit
        # end
    end
    
    def edit

    end
    
    private
    
    # def set_lesson
    #     @lesson = Lesson.find(params[:id])
    # end
    
    def set_params
        params.require(:lesson).permit(:title,:level,:category,:started_at,:description,:price,:instructor,:limits,:image)
    end
end

app/controllers/gym_apps_controller.rb
class GymAppsController < UserController
  
  before_action :authenticate_user!
  
  def index
    @user_reservations = User.where(user_id: session[:user_id])
  end
end

app/helpers/gym_app_helper.rb
module GymAppHelper
end

app/views/gym_apps/index.html.erb
<div class="container">
    <div class="content">
        <div class="show-image mypage-title">
            <h2 style="font-family:'Impact'">MENU</h2>
            <p>現在の所持ポイント: <span><%= current_user.point %></span></p>
            <ul class = mypage-memu>
                <li><%= link_to 'レッスン一覧・検索',lessons_path,class:"mypage-list" %></li>
                <li><%= link_to '商品一覧',items_path,class:"mypage-list" %></li>
                <li><%= link_to '予約済みレッスン',reservations_path,class:"mypage-list" %></li>
            </ul>
        </div>
        <div class="description">
            <div class="container mypage-title">
                <h1 style="font-family:'Impact'">My Page title</h1>
                
                <h2>sub title</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor 
                    in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, 
                    sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                <h2>sub title</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor 
                    in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, 
                    sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                <h2>sub title</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor 
                    in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, 
                    sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                <h2>sub title</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor 
                    in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, 
                    sunt in culpa qui officia deserunt mollit anim id est laborum.</p>                
            </div>
        </div>
    </div>
</div>