config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      confirmations: 'users/confirmations'
    }
    
  root to:'gym_apps#index'
  resources :gym_apps
  get "/lessons",to:"lessons#index"
  get "/lessons/:id",to:"lessons#show",as:"lesson"
  get "/items",to:"items#index"
  get "/items/:id",to:"items#show",as:"item"
  get "/points",to:"points#index"
  resources :reservations, only: [:index,:show, :create, :destroy]
    namespace :management do
        resources :lessons
        resources :items
        get "/authenticate",to:"session#new"
        post "/authenticate",to:"session#create"
        resources :users do
          member do
            post "points",to:"users#point"
          end
        end

        get "/logout",to:"session#destroy"
        
    end
    get "/login",to:"session#new"
end

app/models/lesson.rb
class Lesson < ApplicationRecord
    include Discard::Model
    default_scope -> { kept }
    has_many :reservations
    has_many :users,through: :reservations
    has_one_attached :image

    validates :title,presence: true,length: {maximum: 20}
    validates :level,presence: true
    validates :category,presence: true
    validates :started_at,presence: true
    validates :description,presence: true
    validates :price,presence: true
    validates :instructor,presence: true
    validates :limits,presence: true
    
end

app/controllers/gym_apps/lessons_controller.rb
class Management::LessonsController < ManagementController
    # before_action :set_lesson,only:[:show,:edit,:update]

    def index
        @lessons = Lesson.all
        # @lessons = @lessons.where(title: params[:title]) if params[:title].present?
        # @lessons = @lessons.where(started_at: params[:started_at]) if params[:started_at].present?
        # @lessons = @lessons.where(category: params[:category]) if params[:category].present?
    end
    
    def show
        # @lesson = Lesson.find(params[:id])
    end
    
    def new
        @lesson = Lesson.new
    end
    
    def create
        # lesson_params = set_params
        # @lesson = Lesson.new(lesson_params)
        
        # if @lesson.save
        #     flash[:notice] = "登録完了"
        #     redirect_to management_lessons_path
        # else
        #     flash.now[:alert] = "登録失敗"
        #     render :new
        # end
    end
    
    def update
        # @lesson = Lesson.find(params[:id])      
        # lesson_params = set_params
        # if @lesson.update(lesson_params)
        #     flash[:notice] = "レッスン内容を更新しました。"
        #     redirect_to management_lesson_path(@lesson)
        # else
        #     flash.now[:alert] = "更新に失敗しました。"
        #     render :edit
        # end
    end
    
    def edit

    end
    
    private
    
    # def set_lesson
    #     @lesson = Lesson.find(params[:id])
    # end
    
    def set_params
        params.require(:lesson).permit(:title,:level,:category,:started_at,:description,:price,:instructor,:limits,:image)
    end
end

app/controllers/lessons_controller.rb
class LessonsController < UserController
    before_action :set_lesson,only:[:show]

    def index
        @q = Lesson.ransack(params[:q])
        @lessons = @q.result(distinct: true).page(params[:page]).per(5)
    end
    
    def show
        
    end
    
    # def new
    #     @lesson = Lesson.new
    # end
    
    private
    
    def set_lesson
        @lesson = Lesson.find(params[:id])
    end
   
end

app/controllers/management/lessons_controller.rb
class Management::LessonsController < ManagementController
    before_action :set_lesson,only:[:edit,:update,:destroy]

    def index
        @q = Lesson.ransack(params[:q])
        @lessons = @q.result(distinct: true).page(params[:page]).per(5)
    end
    
    def show
        @lesson = Lesson.includes([:users]).find(params[:id])
    end
    
    def new
        @lesson = Lesson.new
    end
    
    def create
        lesson_params = set_params
        @lesson = Lesson.new(lesson_params)
        
        if @lesson.save
            flash[:notice] = "succeed"
            redirect_to management_lessons_path
        else
            flash.now[:alert] = "failed"
            render :new
        end
    end
    
    def update
        # @lesson = Lesson.find(params[:id])      
        lesson_params = set_params
        if @lesson.update(lesson_params)
            flash[:notice] = "Item was successfully updated."
            redirect_to management_lesson_path(@lesson)
        else
            flash.now[:alert] = "Item was unsuccessfully updated."
            render :edit
        end
    end
    
    def edit

    end
    
    def destroy
        @lesson.discard
        flash[:notice] = "Item was successfully destroyed."
        redirect_to management_lessons_path
    end

    
    private
    
    def set_lesson
        @lesson = Lesson.find(params[:id])
    end
    
    def set_params
        params.require(:lesson).permit(:title,:level,:category,:started_at,:description,:price,:instructor,:limits,:image)
    end

end

app/views/lessons/index.html.erb
<div class="container">
    <div class="page-top mb-4">
        <h1>レッスン一覧</h1>
        <%= link_to 'マイページ',gym_apps_path,class:"btn btn-secondary"%>
    </div>
    <h2 class= res-h2>【検索条件入力欄】</h2>
    <div class="card-body">
        <%= search_form_for @q,url: lessons_path do |f| %>
            <p>レッスン名：<%= f.search_field :title_cont, placeholder: "name", class: "card-input" %></p>
            <p>実施日時：<%= f.search_field :started_at_gteq, placeholder: "date", class: "card-input" %></p>
            <p>区分：<%= f.search_field :category_cont, placeholder: "category", class: "card-input" %></p>
            <div class="page-top">
                <%= button_tag sanitize('<i class="fas fa-search"></i>検索'),:type => "submit",:class => "btn btn-primary"%>
            </div>
        <% end %>
    </div>
    <% @lessons.each do |lesson|%>
        <div class="lesson-one">
            <div class="row sampleRow">
                <p class="col-xs-4">レッスン名：<%= lesson.title %></p>
                <p class="col-xs-4">実施日時：<%= lesson.started_at.strftime("%Y/%m/%d %H:%M") %></p>
                <p class="col-xs-4">区分：<%= lesson.category %></p>

                <p class="button-info full-info"><%= link_to "【レッスン詳細】",lesson_path(lesson),class:"link-info" %></p>
                <p class="button-info res-info"><%= link_to "【詳細】",lesson_path(lesson),class:"btn btn-info" %></p>
            </div>
        </div>
    <% end %>    
    <%= paginate @lessons %>
</div>

app/views/lessons/show.html.erb
<div class="container">
    <div class="page-top mb-4">
        <h1><%= @lesson.title%></h1>
        <%= link_to "戻る",lessons_path,class:"btn btn-secondary"%>        
    </div>
    <div class="content mb-5">
        <div class="show-image">
            <%= image_tag @lesson.image if @lesson.image.attached? %>
            <% if current_user.reservations.find_by(lesson_id:@lesson.id) then%>
                <p>このレッスンは予約済です</p>
            <% elsif @lesson.reservations.count >= @lesson.limits %>
                <p>このレッスンは満員です</p>
            <% else %>
                <p><%= link_to "予約する", reservations_path(lesson_id: @lesson.id),method: :post ,data: { confirm: 'Are you sure?'},class:"btn-reservation" %></p>
                <p>※：レッスンを予約する際は実施日の前日までに予約をお願いします。</p>
            <% end %>
        </div>

        <div class="description">
            <h2>----レッスン概要-----</h2>
            <p>担当:<%= @lesson.instructor %></p>
            <p>実施日時：<%= @lesson.started_at.strftime("%Y/%m/%d %H:%M") %>〜</p>
            <p>ランク：<%= @lesson.level %></p>
            <p>区分：<%= @lesson.category %></p>
            <p>上限人数：<%= @lesson.limits %>人</p>
            <p>料金：<%= @lesson.price %></p>
            <p>概要：<%= @lesson.description %></p>
        </div>
    </div>
</div>