config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      confirmations: 'users/confirmations'
    }
    
  root to:'gym_apps#index'
  resources :gym_apps
  get "/lessons",to:"lessons#index"
  get "/lessons/:id",to:"lessons#show",as:"lesson"
  get "/items",to:"items#index"
  get "/items/:id",to:"items#show",as:"item"
  get "/points",to:"points#index"
  resources :reservations, only: [:index,:show, :create, :destroy]
    namespace :management do
        resources :lessons
        resources :items
        get "/authenticate",to:"session#new"
        post "/authenticate",to:"session#create"
        resources :users do
          member do
            post "points",to:"users#point"
          end
        end

        get "/logout",to:"session#destroy"
        
    end
    get "/login",to:"session#new"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>GymApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" 
        crossorigin="anonymous">
        <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="fixed-top">
      <nav class="navbar navbar-expand-lg navbar-light bg-light bg-header">
        <h1>SILVER'S GYM</h1>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <form class="form-inline my-2 my-lg-0">
          <% if user_signed_in? %>
            <%= link_to 'Log out', destroy_user_session_path, method: :delete,class:"btn btn-dark header-btn" %>
          <% else %>
          <div class="header-btn menu-trigger">
            <%= link_to 'Sign up', new_user_registration_path,class:"btn btn-success"%>
            <%= link_to 'Log in', new_user_session_path,class:"btn btn-primary" %>
          </div>
          <% end %>
          </form>
        </div>
      </nav>
    </header>
    <main>
      <div class="container">
        <p class="notice mt-3"><%= notice %></p>
        <p class="alert"><%= alert %></p>
       <%= yield %>
      </div>  
    </main>
    <footer>
        <div class="container">SILVER'S GYM</div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/management.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>GymApp(management)</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
        
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" 
        crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="fixed-top">
      <div class="bg-header">
          <h1>SILVER'S GYM</h1>
          <% if session[:auth] == true %>
            <%= link_to 'Log out',management_logout_path,data:{confirm: '本当にログアウトしますか？'},class:"btn btn-dark header-btn"%>
          <% end%>
      </div>

      <nav>
        <div class="container">
          <% if session[:auth] == true %>
            <div class="management-header">
              <%= link_to 'レッスン一覧',management_lessons_path %>
              <%= link_to '商品一覧',management_items_path %>
              <%= link_to '会員一覧',management_users_path %>
            </div>
          <% end %>
        </div>
      </nav>
    </header>
    <main>
      <div class="container">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield%>    
      </div>      
    </main>
    <footer>
        <div class="container">SILVER'S GYM</div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  </body>
</html>